# Generated by Django 5.2.5 on 2025-11-14 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_is_active_customuser_department_and_more'),
    ]

    operations = [
    ]
